{% set name = "safeint" %}
{% set version = "3.24" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcleblanc/SafeInt/archive/refs/tags/{{ version }}.tar.gz
  sha256: af6c7222a8420f6f87e198dc94791c28da75fe7241b605342c333fd03fd9dea6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  commands:
    - test -f $PREFIX/include/SafeInt.hpp

about:
  home: https://github.com/dcleblanc/SafeInt
  summary: SafeInt is a class library for C++ that manages integer overflows.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
